#!/usr/bin/env bash
#
# Copyright © 2026 DataSQRL (contact@datasqrl.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

flink_args=()
runner_args=()
split_seen=false

for arg in "$@"; do
  if [[ "$split_seen" == false && "$arg" == "--" ]]; then
    split_seen=true
    continue
  fi

  if [[ "$split_seen" == true ]]; then
    runner_args+=("$arg")
  else
    flink_args+=("$arg")
  fi
done

if [[ "$split_seen" == false ]]; then
  runner_args=("${flink_args[@]}")
  flink_args=()
fi

exec flink run "${flink_args[@]}" -c com.datasqrl.flinkrunner.CliRunner /opt/flink/noop.jar "${runner_args[@]}"
