name: Delete GHCR image on PR close

on:
  pull_request:
    types: [closed]

jobs:
  delete-ghcr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        FLINK_PROFILE: [flink-1.19, flink-1.20]

    steps:
      - name: Delete GHCR image
        run: |
          # Convert the repository name to lowercase for GHCR compatibility
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          # Our PR image tag is pr-<number>-<flink_profile>
          TAG="pr-${{ github.event.number }}-${{ matrix.FLINK_PROFILE }}"
          IMAGE="ghcr.io/$REPO/flink-jar-runner:$TAG"

          echo "Attempting to delete image: $IMAGE"

          # Build the Basic Auth header from your PAT credentials
          TOKEN_BASE64="$(echo -n "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_PASSWORD }}" | base64)"

          # Make a GET request (including multiple Accept types) to retrieve the Docker-Content-Digest header
          # We use '-sD -' to capture both headers and body in RAW_RESPONSE
          RAW_RESPONSE=$(curl -sD - \
            -H "Authorization: Basic $TOKEN_BASE64" \
            -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json" \
            "https://ghcr.io/v2/$REPO/flink-jar-runner/manifests/$TAG")

          # Separate headers from body
          HEADERS=$(echo "$RAW_RESPONSE" | sed -n '/^HTTP/,$p' | sed '/^$/q')

          # Extract the Docker-Content-Digest from headers
          DIGEST=$(echo "$HEADERS" | awk '/docker-content-digest:/ { print $2 }' | tr -d $'\r')

          if [[ -z "$DIGEST" ]]; then
            echo "ERROR: No digest found in GHCR response. The image might not exist, or GHCR didn’t return the digest."
            echo "==== HEADERS START ===="
            echo "$HEADERS"
            echo "==== HEADERS END ===="
            exit 1
          fi

          echo "Found digest: $DIGEST"

          # DELETE the image by digest
          DELETE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -X DELETE \
            -H "Authorization: Basic $TOKEN_BASE64" \
            "https://ghcr.io/v2/$REPO/flink-jar-runner/manifests/$DIGEST")

          if [[ "$DELETE_STATUS" -ge 200 && "$DELETE_STATUS" -lt 300 ]]; then
            echo "Image deleted successfully (HTTP $DELETE_STATUS)."
          else
            echo "ERROR: Failed to delete image. HTTP status $DELETE_STATUS"
            exit 1
          fi
