name: Build uber jar

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  uber-jar:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        FLINK_PROFILE: [flink-1.19, flink-1.20]

    env:
      DOCKER_REPO: datasqrl/flink-jar-runner
      VERSION: ${{ github.event_name == 'release' && github.event.action == 'created' && github.ref_name || 'snapshot' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                <servers>
                  <server>
                    <id>github</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.GITHUB_TOKEN }}</password>
                  </server>
                </servers>
              </settings>" > ~/.m2/settings.xml

      - name: Download dependencies
        run: |
          mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies -P${{ matrix.FLINK_PROFILE }}
          mvn -B -f flink-jar-runner/pom.xml org.apache.maven.plugins:maven-resources-plugin:3.3.1:testResources com.marvinformatics:docker-compose-maven-plugin:5.0.0:pull -P${{ matrix.FLINK_PROFILE }}

      - name: Update version
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          mvn -B versions:set -DnewVersion=${{ env.VERSION }}

      - name: Run Maven Build
        run: |
          mvn -B clean install -P${{ matrix.FLINK_PROFILE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./flink-jar-runner/target/
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            IMAGE=ghcr.io/${{ github.repository }}/flink-jar-runner:${{ github.head_ref || github.ref_name }}-${{ matrix.FLINK_PROFILE }}
          else
            IMAGE=${{ env.DOCKER_REPO }}:${{ env.VERSION }}-${{ matrix.FLINK_PROFILE }}
          fi

          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Rename jar file
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          mv target/flink-jar-runner.uber.jar target/flink-jar-runner-${{ env.VERSION }}-${{ matrix.FLINK_PROFILE }}.jar

      - name: Upload to GitHub Release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@v1
        with:
          files: target/flink-jar-runner-${{ env.VERSION }}-${{ matrix.FLINK_PROFILE }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
